/*
 * This file is generated by jOOQ.
 */
package cn.gshkb.shardingsphere.domain;


import cn.gshkb.shardingsphere.domain.tables.TOrder;
import cn.gshkb.shardingsphere.domain.tables.TOrderItem;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ds extends SchemaImpl {

    private static final long serialVersionUID = -469600980;

    /**
     * The reference instance of <code>ds</code>
     */
    public static final Ds DS = new Ds();

    /**
     * 订单
     */
    public final TOrder T_ORDER = cn.gshkb.shardingsphere.domain.tables.TOrder.T_ORDER;

    /**
     * 订单详情
     */
    public final TOrderItem T_ORDER_ITEM = cn.gshkb.shardingsphere.domain.tables.TOrderItem.T_ORDER_ITEM;

    /**
     * No further instances allowed
     */
    private Ds() {
        super("ds", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TOrder.T_ORDER,
            TOrderItem.T_ORDER_ITEM);
    }
}
