/*
 * This file is generated by jOOQ.
 */
package cn.gshkb.shardingsphere.domain;


import cn.gshkb.shardingsphere.domain.tables.TOrder;
import cn.gshkb.shardingsphere.domain.tables.TOrderItem;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>ds</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_ORDER_PRIMARY = Indexes0.T_ORDER_PRIMARY;
    public static final Index T_ORDER_ITEM_PRIMARY = Indexes0.T_ORDER_ITEM_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_ORDER_PRIMARY = Internal.createIndex("PRIMARY", TOrder.T_ORDER, new OrderField[] { TOrder.T_ORDER.ID }, true);
        public static Index T_ORDER_ITEM_PRIMARY = Internal.createIndex("PRIMARY", TOrderItem.T_ORDER_ITEM, new OrderField[] { TOrderItem.T_ORDER_ITEM.ID }, true);
    }
}
