/*
 * This file is generated by jOOQ.
 */
package cn.gshkb.shardingsphere.domain;


import cn.gshkb.shardingsphere.domain.tables.TOrder;
import cn.gshkb.shardingsphere.domain.tables.TOrderItem;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ds
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 订单
     */
    public static final TOrder T_ORDER = cn.gshkb.shardingsphere.domain.tables.TOrder.T_ORDER;

    /**
     * 订单详情
     */
    public static final TOrderItem T_ORDER_ITEM = cn.gshkb.shardingsphere.domain.tables.TOrderItem.T_ORDER_ITEM;
}
