/*
 * This file is generated by jOOQ.
 */
package cn.gshkb.shardingsphere.domain.tables;


import cn.gshkb.shardingsphere.domain.Ds;
import cn.gshkb.shardingsphere.domain.Indexes;
import cn.gshkb.shardingsphere.domain.Keys;
import cn.gshkb.shardingsphere.domain.tables.records.TOrderItemRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 订单详情
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderItem extends TableImpl<TOrderItemRecord> {

    private static final long serialVersionUID = 1718179971;

    /**
     * The reference instance of <code>ds.t_order_item</code>
     */
    public static final TOrderItem T_ORDER_ITEM = new TOrderItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TOrderItemRecord> getRecordType() {
        return TOrderItemRecord.class;
    }

    /**
     * The column <code>ds.t_order_item.id</code>. 主键
     */
    public final TableField<TOrderItemRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>ds.t_order_item.user_id</code>. 用ID
     */
    public final TableField<TOrderItemRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "用ID");

    /**
     * The column <code>ds.t_order_item.order_id</code>. 订单ID
     */
    public final TableField<TOrderItemRecord, Integer> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGER, this, "订单ID");

    /**
     * The column <code>ds.t_order_item.name</code>. 姓名
     */
    public final TableField<TOrderItemRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "姓名");

    /**
     * The column <code>ds.t_order_item.create_at</code>. 创建时间
     */
    public final TableField<TOrderItemRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>ds.t_order_item.update_at</code>. 更新时间
     */
    public final TableField<TOrderItemRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>ds.t_order_item.version</code>. 版本号
     */
    public final TableField<TOrderItemRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT, this, "版本号");

    /**
     * The column <code>ds.t_order_item.del_flag</code>. 删除标记
     */
    public final TableField<TOrderItemRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT, this, "删除标记");

    /**
     * Create a <code>ds.t_order_item</code> table reference
     */
    public TOrderItem() {
        this(DSL.name("t_order_item"), null);
    }

    /**
     * Create an aliased <code>ds.t_order_item</code> table reference
     */
    public TOrderItem(String alias) {
        this(DSL.name(alias), T_ORDER_ITEM);
    }

    /**
     * Create an aliased <code>ds.t_order_item</code> table reference
     */
    public TOrderItem(Name alias) {
        this(alias, T_ORDER_ITEM);
    }

    private TOrderItem(Name alias, Table<TOrderItemRecord> aliased) {
        this(alias, aliased, null);
    }

    private TOrderItem(Name alias, Table<TOrderItemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("订单详情"));
    }

    public <O extends Record> TOrderItem(Table<O> child, ForeignKey<O, TOrderItemRecord> key) {
        super(child, key, T_ORDER_ITEM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ds.DS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_ORDER_ITEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TOrderItemRecord, Long> getIdentity() {
        return Keys.IDENTITY_T_ORDER_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TOrderItemRecord> getPrimaryKey() {
        return Keys.KEY_T_ORDER_ITEM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TOrderItemRecord>> getKeys() {
        return Arrays.<UniqueKey<TOrderItemRecord>>asList(Keys.KEY_T_ORDER_ITEM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItem as(String alias) {
        return new TOrderItem(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItem as(Name alias) {
        return new TOrderItem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TOrderItem rename(String name) {
        return new TOrderItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOrderItem rename(Name name) {
        return new TOrderItem(name, null);
    }
}
