/*
 * This file is generated by jOOQ.
 */
package cn.gshkb.shardingsphere.domain.tables.records;


import cn.gshkb.shardingsphere.domain.tables.TOrderItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单详情
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOrderItemRecord extends UpdatableRecordImpl<TOrderItemRecord> implements Record8<Long, Integer, Integer, String, Timestamp, Timestamp, Long, Boolean> {

    private static final long serialVersionUID = 1716824319;

    /**
     * Setter for <code>ds.t_order_item.id</code>. 主键
     */
    public TOrderItemRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ds.t_order_item.user_id</code>. 用ID
     */
    public TOrderItemRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.user_id</code>. 用ID
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ds.t_order_item.order_id</code>. 订单ID
     */
    public TOrderItemRecord setOrderId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.order_id</code>. 订单ID
     */
    public Integer getOrderId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ds.t_order_item.name</code>. 姓名
     */
    public TOrderItemRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.name</code>. 姓名
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ds.t_order_item.create_at</code>. 创建时间
     */
    public TOrderItemRecord setCreateAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>ds.t_order_item.update_at</code>. 更新时间
     */
    public TOrderItemRecord setUpdateAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>ds.t_order_item.version</code>. 版本号
     */
    public TOrderItemRecord setVersion(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>ds.t_order_item.del_flag</code>. 删除标记
     */
    public TOrderItemRecord setDelFlag(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>ds.t_order_item.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Integer, String, Timestamp, Timestamp, Long, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Integer, Integer, String, Timestamp, Timestamp, Long, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TOrderItem.T_ORDER_ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TOrderItem.T_ORDER_ITEM.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TOrderItem.T_ORDER_ITEM.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TOrderItem.T_ORDER_ITEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TOrderItem.T_ORDER_ITEM.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TOrderItem.T_ORDER_ITEM.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TOrderItem.T_ORDER_ITEM.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return TOrderItem.T_ORDER_ITEM.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value3(Integer value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value6(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value7(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord value8(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TOrderItemRecord values(Long value1, Integer value2, Integer value3, String value4, Timestamp value5, Timestamp value6, Long value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOrderItemRecord
     */
    public TOrderItemRecord() {
        super(TOrderItem.T_ORDER_ITEM);
    }

    /**
     * Create a detached, initialised TOrderItemRecord
     */
    public TOrderItemRecord(Long id, Integer userId, Integer orderId, String name, Timestamp createAt, Timestamp updateAt, Long version, Boolean delFlag) {
        super(TOrderItem.T_ORDER_ITEM);

        set(0, id);
        set(1, userId);
        set(2, orderId);
        set(3, name);
        set(4, createAt);
        set(5, updateAt);
        set(6, version);
        set(7, delFlag);
    }
}
